"""Add airplane table

Revision ID: ac9918b89ceb
Revises: 9e1a5aeb1d1e
Create Date: 2022-06-08 17:04:03.801649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9918b89ceb'
down_revision = '9e1a5aeb1d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airplane',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=120), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('model_code', sa.String(length=120), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airplane_registration_number'), 'airplane', ['registration_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_airplane_registration_number'), table_name='airplane')
    op.drop_table('airplane')
    # ### end Alembic commands ###
