"""Add range column to airplane table

Revision ID: d0af36875105
Revises: ac9918b89ceb
Create Date: 2022-06-09 08:40:48.612646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0af36875105'
down_revision = 'ac9918b89ceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airplane', sa.Column('range', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airplane', 'range')
    # ### end Alembic commands ###
