"""Add roles column and drop admin column

Revision ID: d8a41be3e4c9
Revises: 0397d0f09b93
Create Date: 2022-05-30 08:49:28.813843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a41be3e4c9'
down_revision = '0397d0f09b93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.String(length=10), nullable=True))
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.BOOLEAN(), nullable=True))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
