"""empty message

Revision ID: fe87d3f7a88b
Revises: 9e1a5aeb1d1e
Create Date: 2022-06-07 09:01:09.134641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe87d3f7a88b'
down_revision = '9e1a5aeb1d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airplane',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=120), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('model_code', sa.String(length=120), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('airplane')
    # ### end Alembic commands ###
